# Generated by Django 4.1.5 on 2023-01-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_blog_category_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
