# Generated by Django 4.1.5 on 2023-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_category_slug_alter_blog_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="slug",),
        migrations.RemoveField(model_name="category", name="slug",),
        migrations.AlterField(
            model_name="blog", name="image", field=models.ImageField(upload_to="blogs"),
        ),
    ]
